name: tuda
description: URL-shortener service with Notion table as a database
version: 1.0.6
homepage: https://github.com/parabolahq/tuda

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  http: ^0.13.4
  neat_periodic_task: ^2.0.0
  sentry: ^6.0.1

dev_dependencies:
  lints: ^1.0.0
