name: CI to GHCR and CD to Server

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_ADDRESS }}
          username: root
          password: ${{ secrets.REMOTE_HOST_PASSWORD }}
          script: sh redeploy_tuda.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Number of lines
        run: git ls-files | xargs wc -l